name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno Version 1.6.0
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.6.0
      - name: Install dext
        run: |
          deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext https://deno.land/x/dext@0.10.1/cli.ts
      - name: Build site
        run: |
          dext build
          dext export netlify
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Downlaod artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: akeo.me
