name: Lint and Test
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno Version 1.6.0
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.6.0
      - name: Lint modules
        run: |
          deno fmt --ignore=.dext,dist
      - name: Test modules
        run: |
          deno test --allow-none
